### ISSUE TITLE
serveur crashed

### ISSUE THREAD

**Issue by croziors** [McJty/McJtyLib#73] opened 2018-05-21 17:00 UTC
Hello,
https://pastebin.com/6uE1vbhB
/home/minecraft/./crash-reports/crash-2018-05-21_16.29.52-server.txt 
 https://pastebin.com/66zxYYC3

**Comment by croziors** [comment] 2018-05-21 17:25
other witouth journeymap
 https://pastebin.com/3ma6pWj0  crash https://pastebin.com/jPWbjEzi

**Comment by McJty** [comment] 2018-05-22 02:56
Can you describe what exactly you are doing?

**Comment by josephcsible** [comment] 2018-05-22 02:59
No need; I know what's going on.

https://github.com/McJtyMods/RFTools/blob/65a43ef89ce130bb7029f17779bf6afd311cf985/src/main/java/mcjty/rftools/blocks/logic/generic/LogicTileEntity.java#L29

https://github.com/McJtyMods/McJtyLib/blob/e0694f5da022694100aac1de589acfd566ae680a/src/main/java/mcjty/lib/varia/Logging.java#L72-L74

Having `player` be null causes a crash there. I'm not sure why this hasn't burned us before though, as there's several places in the code where that's true.

(I'm not sure whether we should fix this by stopping passing `null`, or by making `null` do something sensible.)

**Comment by JBSTheGamer** [comment] 2018-10-30 20:38
Im having the exact same crash with my side here is my crash report https://paste.dimdev.org/humetecigu.mccrash

**Comment by josephcsible** [comment] 2018-10-30 20:57
Duplicate of McJtyMods/RFTools#1844. This has been fixed since McJtyLib 3.0.6. @joshuasuperboy you're way out of date. Update and it will be fixed for you.

**Closed as completed by josephcsible** 2018-10-30 20:57 UTC
