### ISSUE TITLE
1.10.2 Server keeps crashing

### ISSUE THREAD

**Issue by Tyranotile** [McJty/McJtyLib#92] opened 2018-12-16 20:12 UTC
I keep trying to run the server but these messages keep popping up. There were about 4 mods that reacted like this, and when I'd replace Lib with the version it would ask for, it would ask for another, and keep cycling through. 

"net.minecraftforge.fml.common.MissingModsException: Mod deepresonance (DeepResonance) requires [McJtyLib@[1.10-2.1.0,)]"

"net.minecraftforge.fml.common.MissingModsException: Mod xnet (XNet) requires [mcjtylib_ng@[2.3.11,)]"

**Comment by josephcsible** [comment] 2018-12-16 20:15
Please post a full mod list including versions. The problem is likely that one of the mods that depends on McJtyLib is too old, so updating McJtyLib and all of its dependencies will probably fix it.

**Comment by Tyranotile** [comment] 2018-12-16 20:45
For all of the mods I'm listing, it's 1.10.2, most updated versions.
Actually Additions, Applied Energistics 2, AutoRegLib, Baubles, Better Builders Wands, Biomes O Plenty, Blood Magic, Bookshelf, Botania, Chameleon, Code Chicken Core, Code Chicken Lib, Compatlayer, Craft Tweaker, Dark Utilities, Deep Resonance, Elec Core, Ender Core, Ender IO, Ender Storage, Extra Utilities, Extreme Reactors, Fast Leaf Decay, Forestry, FTBLib, FTBUtilities, Gravestone, Guide-API, Immersive Engineering, Industrial Craft, Inventory Sorter, Iron Backpacks, Iron Chest, JEI (3.14.2.398), JEI Bees, Journey Map, JER, LL Overlay Reloaded, Mantle, mcjtylib (This is 2.3.11), MC MultiPart, Morpheus, Not Enough Wands, Pam's Harvest Craft, Psi, Quark, Railcraft, Ranged Pumps, Refined Storage, Resource Loader, RF Tools, RF Tools Control, RF Tools dim, Storage Drawers, Tinkers' Construct, xnet, and Zero Core. I'll also attach a screenshot of all of the files.

**Comment by Tyranotile** [comment] 2018-12-16 20:45
![image](https://user-images.githubusercontent.com/45923026/50058660-9e349f80-0149-11e9-8682-43b2d848d67e.png)

![image](https://user-images.githubusercontent.com/45923026/50058666-a5f44400-0149-11e9-8d5b-560ab27b37ab.png)

**Comment by josephcsible** [comment] 2018-12-16 20:58
> For all of the mods I'm listing, it's 1.10.2, **most updated versions**.

That's not true, and that's the problem. You're on McJtyLib 2.3.11, and the latest for 1.10/1.11 is 2.5.3. You're on XNet 1.3.2, and the latest for 1.10/1.11 is 1.5.0. You're on Deep Resonance 1.3.1, and the latest for 1.10/1.11 is 1.4.9. You're on CompatLayer 0.2.9, and the latest for 1.10 is 0.3.1. You're on NotEnoughWands 1.4.0, and the latest for 1.10/1.11 is 1.5.5. You're on RFTools 5.59, and the latest for 1.10/1.11 is 7.16. You're on RFTools Control 1.5.2, and the latest for 1.10/1.11 is 1.7.0. You're on RFTools Dimensions 4.45, and the latest for 1.10/1.11 is 5.05. Upgrade all of those and see if the problem goes away.

**Comment by Tyranotile** [comment] 2018-12-16 21:07
Ok, I'll do that real quick and see if it gets fixed.

**Comment by Tyranotile** [comment] 2018-12-16 21:31
So I get this error when I try to run the Universal File through a .bat file, since running it normally doesn't allow enough space.
[crash-2018-12-16_16.30.38-server.txt](https://github.com/McJtyMods/McJtyLib/files/2683979/crash-2018-12-16_16.30.38-server.txt)

**Comment by josephcsible** [comment] 2018-12-16 21:36
That's related to FTB Lib/FTB Utilities. It has nothing to do with McJtyLib or any of McJty's other mods. (Try upgrading/removing them to see if it goes away though.)

**Comment by Tyranotile** [comment] 2018-12-16 21:37
Ok, thanks.

**Comment by Tyranotile** [comment] 2018-12-16 21:51
Now whenever I try to run the server nothing happens. The window opens for a second and immediately closes. There isn't a crash report for it either.

**Comment by josephcsible** [comment] 2018-12-16 21:52
Check the regular logs.

**Comment by Tyranotile** [comment] 2018-12-16 21:54
The first is the log from the .bat file run, the second is just through the normal Java executable. This isn't a very fun experience.
[fml-server-latest.log](https://github.com/McJtyMods/McJtyLib/files/2683997/fml-server-latest.log)

[latest.log](https://github.com/McJtyMods/McJtyLib/files/2683998/latest.log)

**Comment by josephcsible** [comment] 2018-12-16 22:05
The first log doesn't make it obvious what's wrong, but my guess is it's something to do with ElecCore. See if it loads if you temporarily remove ElecCore as well as Deep Resonance and any other mods that depend on it. If that works, then please close this issue and open a new one at https://github.com/Elecs-Mods/ElecCore/issues. If that doesn't work, please post the new log.

The second log failed because it didn't have enough memory (which you already knew).

**Comment by Tyranotile** [comment] 2018-12-16 22:06
Yeah, the memory problem really irks me. I'll try with the ElecCore stuff.

**Comment by Tyranotile** [comment] 2018-12-16 22:24
Does this mean anything to you? Because it doesn't look good to me.
![image](https://user-images.githubusercontent.com/45923026/50059623-5f0d4b00-0157-11e9-8014-7b6856f901a7.png)

**Comment by Tyranotile** [comment] 2018-12-16 22:26
That's obviously not the right picture. It didn't load right I guess.

**Comment by Tyranotile** [comment] 2018-12-16 22:28
I think I've figured it out. The mods used in the client aren't the same as the ones in the server. I need to update the client mods.

**Comment by josephcsible** [comment] 2018-12-16 23:10
Okay, keep me posted as to whether that worked.

**Closed as completed** 2018-12-30 23:22 UTC
Labels: needs response from reporter
