### ISSUE TITLE
LAN game hang on game exit

### ISSUE THREAD

**Issue by ChaoticLogic** [McJty/McJtyLib#90] opened 2018-10-08 04:00 UTC
After playing a LAN game with one other person and the person has left, clicking Save & Exit causes game to hang. Log reveals:

> [22:58:09] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up all world data: 1 data blobs

Nothing follows.

**Comment by McJty** [comment] 2018-10-08 04:23
And why is this a bug in McJtyLib?

**Comment by McJty** [comment] 2018-10-08 04:23
It is not because the last thing it does is cleaning up that data that it is McJtyLib causing this. I've seen this problem too in other packs that don't even have my mods

**Comment by josephcsible** [comment] 2018-10-08 21:56
Unless you can confirm that this stops happening if you remove McJtyLib and its dependencies, this will be closed.

**Comment by ChaoticLogic** [comment] 2018-10-09 03:29
I apologize for the delay in response. I work long hours to provide for my
family.

By all means, please, close it. You seem very defensive as though I have
accused you of something. I apologize if it came across that way; that was
not my intention.


*End of Line*

**Comment by McJty** [comment] 2018-10-09 03:33
Sorry for that but it is not the first time one of my mods has been accused of causing a bug simply because it prints out something to the log at the wrong time. Anyway, it is not totally impossible that it *is* caused by McJtyLib but we need better proof for that and a better way to reproduce it. So I'm closing it for now and will reopen as needed.

**Closed as completed by McJty** 2018-10-09 03:33 UTC
