### ISSUE TITLE
I think your mod is an cause of this crash.

### ISSUE THREAD

**Issue by ESTPlayer** [McJty/McJtyLib#78] opened 2018-05-31 21:46 UTC
The crash log is here: https://paste.dimdev.org/uceziselot.txt
minecraft: 1.12.2
forge: 2705
mcjtylib: McJtyLib - 1.12-3.0.0-alpha
rftools: RFTools - 1.12-7.50-alpha

**Comment by josephcsible** [comment] 2018-05-31 22:29
Duplicate of McJtyMods/RFTools#1760 and McJtyMods/RFTools#1765. Already fixed in git, will be fixed in the next release.

**Closed as completed by josephcsible** 2018-05-31 22:29 UTC
Labels: duplicate
