### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by stormcraft1999** [McJty/McJtyLib#174] opened 2024-09-23 22:45 UTC
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2024-09-23 16:26:43
Description: Exception in server tick loop

net.neoforged.fml.ModLoadingException: Loading errors encountered:
	- McJtyLib (mcjtylib) encountered an error while dispatching the net.neoforged.fml.event.config.ModConfigEvent$Loading event
	  java.lang.IllegalStateException: Cannot get config value before config is loaded.

	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:162) ~[loader-4.0.24.jar%2360!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.config.ModConfig.setConfig(ModConfig.java:79) ~[loader-4.0.24.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.config.ConfigTracker.loadConfig(ConfigTracker.java:197) ~[loader-4.0.24.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.config.ConfigTracker.openConfig(ConfigTracker.java:140) ~[loader-4.0.24.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.config.ConfigTracker.lambda$loadConfigs$2(ConfigTracker.java:124) ~[loader-4.0.24.jar%2360!/:4.0] {}
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2351) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:124) ~[loader-4.0.24.jar%2360!/:4.0] {}
	at TRANSFORMER/neoforge@21.1.58/net.neoforged.neoforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:97) ~[neoforge-21.1.58-universal.jar%23279!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:191) ~[server-1.21.1-20240808.144430-srg.jar%23278!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:670) ~[server-1.21.1-20240808.144430-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}

**Comment by McJty** [comment] 2024-09-28 04:22
I cannot reproduce this. However I did release a new version of McJtyLib. Could you try this out? If it still crashes can you give me the full log?

**Comment by McJty** [comment] 2024-10-15 03:07
Closing because of lack of response

**Comment by stormcraft1999** [comment] 2024-10-15 16:40
[crash-2024-10-15_10.33.27-server.txt](https://github.com/user-attachments/files/17381867/crash-2024-10-15_10.33.27-server.txt)
[latest.log](https://github.com/user-attachments/files/17381869/latest.log)

**Comment by McJty** [comment] 2024-10-22 03:20
Finally found the bug and it's fixed now

**Closed as completed by McJty** 2024-10-22 03:20 UTC

**Comment by stormcraft1999** [comment] 2024-10-23 17:22
thank you so much!!!
